### ISSUE TITLE
Exception: user authentication cancelled

### ISSUE THREAD

**Issue by deRightDirection** [OneDrive/onedrive-sdk-csharp#225]
one my own developed uwp-apps shows this error everytime when it tries to sign in to onedrive. The same code for signing in and out for onedrive is used in another app of mine. In this app the proces works perfectly.

i substituted the app-id of the malfunctioning app with the app-id of the app which is working. no difference. So what is going wrong here? I am at the end of my options...

see attached picture as well for information

Summary:

1 c#-class written to sign in and sign out to onedrive
2 uwp-apps use this class
1 one app can sign in perfectly two onedrive with app-ids of both apps
1 one app can't sign in at all to onedrive with all the app-ids

StackTrace:
 at Microsoft.OneDrive.Sdk.Authentication.WebAuthenticationBrokerWebAuthenticationUi.<AuthenticateAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.OneDrive.Sdk.Authentication.OAuthHelper.<GetAuthorizationCodeAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.OneDrive.Sdk.Authentication.MsaAuthenticationProvider.<AuthenticateUserAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.OneDrive.Sdk.Authentication.MsaAuthenticationProvider.<RestoreMostRecentFromCacheOrAuthenticateUserAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.OneDrive.Sdk.Authentication.MsaAuthenticationProvider.<RestoreMostRecentFromCacheOrAuthenticateUserAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at WinUX.CloudServices.OneDrive.OneDriveService.<SigninAndCreateOneDriveClient>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at WinUX.CloudServices.OneDrive.OneDriveService.<Connect>d__12.MoveNext()
![screenhunter_87 may 21 14 05](https://cloud.githubusercontent.com/assets/3999790/26283794/9b624224-3e2e-11e7-8a65-b181c2195639.jpg)

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #259 for more information
