### ISSUE TITLE
Authentication using Refresh Token

### ISSUE THREAD

**Issue by yuribb** [OneDrive/onedrive-sdk-csharp#38]
Hello. It is possible to authenticate in client by using refresh token, taken in previous session? And if it possible, please write an example how to authenticate. Thank you in advance.

**Comment by ginach** [comment]
It is possible. You'll want to use OneDriveClient.GetSilentlyAuthenticatedMicrosoftAccountClient:

```csharp
await OneDriveClient.GetSilentlyAuthenticatedMicrosoftAccountClient(
    clientId,
    returnUrl,
    scopes,
    refreshToken)
```
AAD auth doesn't have the functionality yet. It's coming with App-only authentication (#36).

**Comment by yuribb** [comment]
Thank you for your answer. It really helped for me.

**Comment by yuribb** [comment]
Hello again. I try to authenticate by using my web application.
The code looks like:

`m_client = await
                        Microsoft.OneDrive.Sdk.OneDriveClient.GetSilentlyAuthenticatedMicrosoftAccountClient(
                                ClientId,
                                ReturnUrl,
                                MsaScopes,
                                networkCredential.Password);`

Where ClientId is my web application ClientId.
ReturnUrl is "https://login.live.com/oauth20_desktop.srf" or my registred redirectUrl or "https://localhost/return".
MsaScopes is "onedrive.readwrite", "wl.offline_access". And when i authorized, i add it to request.
networkCredential.Password is my refresh token. But they crashed with OneDriveException with  error Code: GeneralException
Message: Unexpected exception returned from the service.
What the error could it be?

**Comment by ginach** [comment]
This error is actually thrown when we get an unexpected error trying to call the OneDrive API, after authentication. When there's no error body in the API response we throw GeneralException. Could you take a look at what the HTTP status code you're seeing is?

**Comment by yuribb** [comment]
Additional Data: null
Code: General Exception
Inner Error: null
Message: Unexpected exception returned from the service.
Stack Trace:
at Microsoft.OneDrive.Sdk.HttpProvider.<SendAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.OneDrive.Sdk.AuthenticationProvider.<SendTokenRequestAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.OneDrive.Sdk.AuthenticationProvider.<ProcessCachedAccountSessionAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.OneDrive.Sdk.AuthenticationProvider.<AuthenticateAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.OneDrive.Sdk.BaseClient.<AuthenticateAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.OneDrive.Sdk.OneDriveClient.<GetSilentlyAuthenticatedMicrosoftAccountClient>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

I can' see the HTTP status code in this exception. Where i can take it?

**Comment by yuribb** [comment]
Update:
I have solved the problem. Successful authentication required using overload that takes param "ClientSecret".

**Comment by mybluedog** [comment]
Hi @ginach.  Can you please provide a time frame for when you expect to implement refresh token auth for Business?  As our app runs as a service, we can see no other way to access the user's OneDrive on a long-term basis.

**Comment by sureshotday** [comment]
I am also facing the same problem. @yuribb How did you solve it? Can you please post the code?

**Comment by nsouren** [comment]
Hi there,
Is it possible to authenticate the AAD client by using refresh token?
I do not see any method like GetSilentlyAuthenticatedMicrosoftAccountClient() for OneDrive for Business.

**Comment by ginach** [comment]
Fixed in latest package push.

**Comment by nsouren** [comment]
Could you please clarify, why Business account support is added into "OneDriveSdk.WindowsForms.dll" assembly and not in "OneDriveSdk.dll"?
Also why "OneDriveSdk.WindowsForms.dll" is not available in .NET4.5 Nuget package (available only in .NET4.5.1)?

**Comment by RussWalton** [comment]
Can you tell me which version of the SDK this is working with? I'm going around in circles here. I've just created a new UWP app, got the latest NuGet Onedrive SDK and Authentication SDK (v2.0.4 and v1.0.7 respectively) but I'm not seeing any of the static or instance methods above, such as 
OneDriveClient.GetSilentlyAuthenticatedMicrosoftAccountClient

![dis1](https://cloud.githubusercontent.com/assets/19670668/20032943/e7af87b4-a38c-11e6-96ae-dbd2f701f34d.PNG)


or 
this.oneDriveClient.AuthenticateAsync();

![dis2](https://cloud.githubusercontent.com/assets/19670668/20032944/ea50de5a-a38c-11e6-8394-676592fa3f0d.PNG)


I'm clearly missing something here.
Thanks,
Russ

**Comment by cdmayer** [comment]
This thread is very old. This is the pattern you should be using with the Auth Adapter: https://github.com/OneDrive/onedrive-sdk-dotnet-msa-auth-adapter#getting-started

```csharp
var msaAuthenticationProvider = new MsaAuthenticationProvider(
        clientId,
        returnUrl,
        scopes);
await msaAuthenticationProvider.AuthenticateUserAsync();
oneDriveClient = new OneDriveClient("https://api.onedrive.com/api/1.0", msaAuthenticationProvider);
```
