### ISSUE TITLE
Bad Exception Error

### ISSUE THREAD

**Issue by minimalisticMe** [OneDrive/onedrive-sdk-csharp#50]
When uploading a file, I used to encounter an Error:
`{System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at Microsoft.OneDrive.Sdk.BaseRequest.InitializeUrl(String requestUrl)
   at Microsoft.OneDrive.Sdk.BaseRequest..ctor(String requestUrl, IBaseClient client, IEnumerable' 1 options)
   at Microsoft.OneDrive.Sdk.ItemContentRequestBuilder.Request()
   at OneDriveClass.myOneDrive.<uploadFile>d__8.MoveNext()}`

This was a `System.Exception` and not a `Microsoft.OneDrive.Sdk.OneDriveException`. The issue was, that I forgot to check, if I'm authenticated to upload:

` if (!this.oneDriveClient.IsAuthenticated)
            {
                await this.oneDriveClient.AuthenticateAsync();
            }`

Adding these lines prevented the error.

Maybe you can make this an Error, that get's triggered in `Microsoft.OneDrive.Sdk.OneDriveException` when one forgot to authenticate and give the Exception a better description (so I as a dev know, what's really wrong).

**Comment by ginach** [comment]
This is fixed in version 1.1.29. Please re-open if you're still seeing issues.
